# Setup
title:        时间煮雨
tagline:      Hope we can change something big with tiny point.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Rocky Yang
  url:        http://www.yangjian.co

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
